version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4

    working_directory: /go/src/{{REPO_NAME}}
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}

      - run:
          name: Check code formatting with go fmt
          command: |
            make fmt

      - run:
          name: Run unit tests
          command: |
            make clean test
            go tool cover -html=build/coverage.out -o build/coverage.html
            mv build/coverage.html /tmp/artifacts

      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts:
          path: /tmp/artifacts
