version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4

    working_directory: /go/src/{{REPO_NAME}}
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}

      - run:
          name: Initialize environment
          command: |
            mkdir -p /tmp/test-results

      - run:
          name: Check code formatting with go fmt
          command: |
            make fmt

      - run:
          name: Run unit tests
          command: |
            gotestsum --format=short-verbose --no-summary=output --junitfile /tmp/test-results/gotestsum-report.xml

      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_test_results:
          path: /tmp/test-results
